import Head from 'next/head'
import { ContractAddress } from "../constant/contract_address";
import { useSelector } from 'react-redux';
import { useEffect, useState } from 'react';
import Web3 from 'web3';
import Market from '../artifacts/contracts/Market.sol/Market.json';
import NFT from '../artifacts/contracts/NFT.sol/NFT.json';
import axios from 'axios';
import { Grid, Container, Card, Box, Typography } from '@mui/material';
import Link from 'next/link';


export default function Home() {

  const user = useSelector(state => state.userReducer);
  const [nfts, setNfts] = useState([]);
  const NFTContractAddress = ContractAddress.NFTContract
  const MarketContractAddress = ContractAddress.MarketContract

  let nftContract = null;
  let marketContract = null;

  const connectWithContract = async () => {
    if (user.isUserConnected) {

      var web3 = new Web3(window.web3.currentProvider);
      let nftCon = new web3.eth.Contract(NFT.abi, NFTContractAddress);
      let marketCon = new web3.eth.Contract(Market.abi, MarketContractAddress);

      nftContract = nftCon;
      marketContract = marketCon;

      console.log('nftCon', nftContract);
      console.log('marketCon', marketContract);
      readNFTs();
    }
  }

  const readNFTs = async () => {
    const res = await marketContract.methods.getAllNFTs().call()
    console.log('res : ', res);
    const items = await Promise.all(res.map(async i => {
      const uri = await nftContract.methods.tokenURI(i.tokenId).call()
      const meta = await axios.get(uri);
      const item = {

        name: meta.data.name,
        image: meta.data.image,
        tokenId: i.tokenId,
        description: meta.data.description,
      };
      return item;
    }));
    console.log('items : ', items)
    setNfts(items);
  }

  useEffect(() => {
    connectWithContract();
  }, [])

  return (
    <div className='container mx-auto'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid container spacing={2}>
          {nfts && nfts.map(nft => (<>
            <Grid item xs={6} md={3}>
              <Link href={`details/${nft.itemId}`}>
                <Card>
                  <Box px={4} py={2}>
                    <Typography>{nft.name}</Typography>
                    <img src={`${nft.image}`}
                      srcSet={`${nft.image}`}
                      height={200} width={200} />
                    <Typography>{nft.description}</Typography>
                  </Box>
                </Card>
              </Link>
            </Grid>
          </>))}
        </Grid>
      </Container>
    </div>
  )
}
